"use client";
import { useEffect, useState } from "react";
type Locale="zh-TW"|"zh-CN"|"en"|"vi";
const dict:Record<string,Record<string,string>>={
"zh-CN":{"員工":"员工","人資":"人资","薪資":"薪资","請假":"请假","招募":"招聘","資料":"资料","報表":"报表","簽核":"审批","工時":"工时","結算":"结算","清冊":"清册","開始測試":"开始测试","互動":"互动","部門":"部门","職稱":"职称","在職":"在职","待審核":"待审核","已核准":"已批准"},
en:{"員工名冊":"Employee Directory","招募流程":"Recruitment","薪資試算":"Payroll Calculator","請假簽核":"Leave Approval","雲端打卡":"Cloud Clock-in","外勤定位":"Field Location","異常判斷":"Exception Detection","排班管理":"Scheduling","工時計薪":"Time & Payroll","主管儀表板":"Manager Dashboard","派遣員工資料":"Dispatched Staff","客戶與工地":"Clients & Sites","派工排班":"Dispatch Scheduling","出勤工時":"Attendance Hours","結算調整":"Settlement Adjustments","薪資清冊":"Payroll Register","請款報表":"Billing Reports","管理分析":"Management Analytics","開始測試":"Start Demo","開始派工":"Start Dispatch","操作 Demo":"Try Demo","進入 Demo":"Enter Demo","查看功能":"View Features","查看招募":"View Recruitment","系統模組":"Modules","功能架構":"Features","互動 Demo":"Interactive Demo","新增員工":"Add Employee","新增":"Add","確認":"Confirm","取消":"Cancel","姓名":"Name","部門":"Department","職稱":"Job Title","狀態":"Status","在職":"Active","待審核":"Pending","已核准":"Approved","薪資":"Payroll","請假":"Leave","招募":"Recruitment","員工":"Employee","人資":"HR","資料":"Data","報表":"Reports","管理":"Management","簽核":"Approval","出勤":"Attendance","派遣":"Dispatch","工時":"Hours","結算":"Settlement","清冊":"Register","平台":"Platform","工作台":"Workspace","功能":"Features"},
vi:{"員工名冊":"Danh sách nhân viên","招募流程":"Quy trình tuyển dụng","薪資試算":"Tính lương","請假簽核":"Duyệt nghỉ phép","雲端打卡":"Chấm công đám mây","外勤定位":"Định vị công tác","異常判斷":"Phát hiện bất thường","排班管理":"Quản lý ca làm","工時計薪":"Giờ công và lương","主管儀表板":"Bảng điều khiển quản lý","派遣員工資料":"Nhân viên phái cử","客戶與工地":"Khách hàng và công trường","派工排班":"Lịch điều phối","出勤工時":"Giờ chấm công","結算調整":"Điều chỉnh quyết toán","薪資清冊":"Bảng lương","請款報表":"Báo cáo thanh toán","管理分析":"Phân tích quản trị","開始測試":"Bắt đầu dùng thử","開始派工":"Bắt đầu điều phối","操作 Demo":"Dùng thử Demo","進入 Demo":"Vào Demo","查看功能":"Xem tính năng","查看招募":"Xem tuyển dụng","系統模組":"Mô-đun","功能架構":"Tính năng","互動 Demo":"Demo tương tác","新增員工":"Thêm nhân viên","新增":"Thêm","確認":"Xác nhận","取消":"Hủy","姓名":"Họ tên","部門":"Phòng ban","職稱":"Chức danh","狀態":"Trạng thái","在職":"Đang làm","待審核":"Chờ duyệt","已核准":"Đã duyệt","薪資":"Lương","請假":"Nghỉ phép","招募":"Tuyển dụng","員工":"Nhân viên","人資":"Nhân sự","資料":"Dữ liệu","報表":"Báo cáo","管理":"Quản lý","簽核":"Phê duyệt","出勤":"Chấm công","派遣":"Phái cử","工時":"Giờ công","結算":"Quyết toán","清冊":"Danh sách","平台":"Nền tảng","工作台":"Không gian làm việc","功能":"Tính năng"}};
const originals=new WeakMap<Node,string>();
function translate(text:string,locale:Locale){let out=text;if(locale!=="zh-TW")for(const [a,b] of Object.entries(dict[locale]).sort((x,y)=>y[0].length-x[0].length))out=out.split(a).join(b);return out.replace(/Jvision|JVision(?! HR)/g,"JVision HR").replaceAll("JVision HR HR","JVision HR")}
export function LanguageSwitcher(){const [locale,setLocale]=useState<Locale>("zh-TW");useEffect(()=>{document.documentElement.lang=locale;const apply=(root:Node)=>{const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n:Node|null;while(n=w.nextNode()){const p=n.parentElement;if(!p||p.closest(".language-switcher")||["SCRIPT","STYLE"].includes(p.tagName))continue;if(!originals.has(n))originals.set(n,n.textContent||"");n.textContent=translate(originals.get(n)||"",locale)}};apply(document.body);const o=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(apply)));o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[locale]);return <div className="language-switcher" style={{position:"fixed",right:16,bottom:16,zIndex:9999,display:"flex",gap:8,alignItems:"center",background:"white",padding:"8px 10px",border:"1px solid #d8e1ec",borderRadius:10,boxShadow:"0 8px 24px #10204022"}}><b style={{color:"#1769e0",fontSize:12}}>JVision HR</b><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as Locale)} style={{padding:"6px",borderRadius:7,border:"1px solid #cdd8e5"}}><option value="zh-TW">繁中</option><option value="zh-CN">简中</option><option value="en">English</option><option value="vi">Tiếng Việt</option></select></div>}
